### ISSUE TITLE
fp_out is not initialized when linked as shared object, causes segfault

### ISSUE THREAD

**Issue by dnotq** [Xilinx/platformstats#3]
https://github.com/Xilinx/xlnx_platformstats/blob/2b91c81a82bc06a97f89319bff82587af7f2f212/src/xlnx_platformstats.c#L23

The change in 2022 to use fprintf against the local FILE *fp_out breaks when complied and used as a shared object (fp_out is never initialized to an open file).  For example, anything written in python like the KRIA Dashboard, etc..

At the very least fp_out should probably default to being set to stdout in the init() function, and a new function introduced to change the output file pointer.  Or, the file pointer could be passed into the init() function, but that would break the API and all code using the lib would need to be updated.

A simple program to demonstrate the segfault:

```
import sys
from xlnx_platformstats import xlnx_platformstats as xs

import faulthandler
faulthandler.enable()

xs.init()
xs.get_voltages()
xs.deinit()
```

When run from a petalinux build on a KRIA:

```
~$ python test.py 
Fatal Python error: Segmentation fault

Current thread 0x0000ffff96e6e010 (most recent call first):
  File "/usr/lib/python3.9/site-packages/xlnx_platformstats/xlnx_platformstats.py", line 139 in get_voltages
  File "/home/petalinux/test.py", line 8 in <module>
Segmentation fault (core dumped)
```

**Comment by vshpatel** [comment]
Fixed via https://github.com/Xilinx/xlnx_platformstats/commit/3203100934ab978020d821ea6e49778f06ca497b
