### ISSUE TITLE
No ina260_u14 device/node on KRIA SOM

### ISSUE THREAD

**Issue by dnotq** [Xilinx/platformstats#4]
https://github.com/Xilinx/xlnx_platformstats/blob/2b91c81a82bc06a97f89319bff82587af7f2f212/src/xlnx_platformstats.c#L936

The KRIA SOM does not appear to have the hard-coded `ina260_u14` device or node.  Possibly the SOM hardware has changed since this code was written?  Any request for voltage, current, or power result in this message:

"no hwmon device found for ina260_u14 under /sys/class/hwmon"

Unless there is a specific driver that needs to be enabled in the PetaLinux kernel config, these are the available `hwmon` devices on the K26 SOM using the Xilinx K26 BSP and 2022.2 PetaLinux:

```
xilinx-k26-som-20222:/sys/class/hwmon$ ls -la
total 0
drwxr-xr-x  2 root root 0 Nov 19  2021 .
drwxr-xr-x 67 root root 0 Nov 19  2021 ..
lrwxrwxrwx  1 root root 0 Nov 19  2021 hwmon0 -> ../../devices/platform/ams/hwmon/hwmon0
lrwxrwxrwx  1 root root 0 Nov 19  2021 hwmon1 -> ../../devices/platform/pwm-fan/hwmon/hwmon1
xilinx-k26-som-20222:/sys/class/hwmon$ ls -la hwmon0/
total 0
drwxr-xr-x 3 root root    0 Nov 19  2021 .
drwxr-xr-x 3 root root    0 Nov 19  2021 ..
lrwxrwxrwx 1 root root    0 May  7 13:47 device -> ../../../ams
-r--r--r-- 1 root root 4096 May  7 13:47 in10_input
-r--r--r-- 1 root root 4096 May  7 13:47 in11_input
-r--r--r-- 1 root root 4096 May  7 13:47 in12_input
-r--r--r-- 1 root root 4096 May  7 13:47 in13_input
-r--r--r-- 1 root root 4096 May  7 13:47 in14_input
-r--r--r-- 1 root root 4096 May  7 13:47 in15_input
-r--r--r-- 1 root root 4096 May  7 13:47 in16_input
-r--r--r-- 1 root root 4096 May  7 13:47 in17_input
-r--r--r-- 1 root root 4096 May  7 13:47 in18_input
-r--r--r-- 1 root root 4096 May  7 13:47 in19_input
-r--r--r-- 1 root root 4096 May  7 13:47 in1_input
-r--r--r-- 1 root root 4096 May  7 13:47 in20_input
-r--r--r-- 1 root root 4096 May  7 13:47 in21_input
-r--r--r-- 1 root root 4096 May  7 13:47 in22_input
-r--r--r-- 1 root root 4096 May  7 13:47 in23_input
-r--r--r-- 1 root root 4096 May  7 13:47 in24_input
-r--r--r-- 1 root root 4096 May  7 13:47 in25_input
-r--r--r-- 1 root root 4096 May  7 13:47 in26_input
-r--r--r-- 1 root root 4096 May  7 13:47 in27_input
-r--r--r-- 1 root root 4096 May  7 13:47 in2_input
-r--r--r-- 1 root root 4096 May  7 13:47 in3_input
-r--r--r-- 1 root root 4096 May  7 13:47 in4_input
-r--r--r-- 1 root root 4096 May  7 13:47 in5_input
-r--r--r-- 1 root root 4096 May  7 13:47 in6_input
-r--r--r-- 1 root root 4096 May  7 13:47 in7_input
-r--r--r-- 1 root root 4096 May  7 13:47 in8_input
-r--r--r-- 1 root root 4096 May  7 13:47 in9_input
-r--r--r-- 1 root root 4096 May  7 13:47 name
lrwxrwxrwx 1 root root    0 May  7 13:47 of_node -> ../../../../../firmware/devicetree/base/ams
drwxr-xr-x 2 root root    0 May  7 13:47 power
lrwxrwxrwx 1 root root    0 Nov 19  2021 subsystem -> ../../../../../class/hwmon
-r--r--r-- 1 root root 4096 May  7 13:47 temp1_input
-r--r--r-- 1 root root 4096 May  7 13:47 temp2_input
-r--r--r-- 1 root root 4096 May  7 13:47 temp3_input
-rw-r--r-- 1 root root 4096 Nov 19  2021 uevent
xilinx-k26-som-20222:/sys/class/hwmon$ ls -la hwmon1/
total 0
drwxr-xr-x 3 root root    0 Nov 19  2021 .
drwxr-xr-x 3 root root    0 Nov 19  2021 ..
lrwxrwxrwx 1 root root    0 May  7 13:47 device -> ../../../pwm-fan
-r--r--r-- 1 root root 4096 May  7 13:47 name
lrwxrwxrwx 1 root root    0 May  7 13:47 of_node -> ../../../../../firmware/devicetree/base/pwm-fan
drwxr-xr-x 2 root root    0 May  7 13:47 power
-rw-r--r-- 1 root root 4096 May  7 13:47 pwm1
lrwxrwxrwx 1 root root    0 Nov 19  2021 subsystem -> ../../../../../class/hwmon
-rw-r--r-- 1 root root 4096 Nov 19  2021 uevent
xilinx-k26-som-20222:/sys/class/hwmon$ cat hwmon0/name 
ams
xilinx-k26-som-20222:/sys/class/hwmon$ cat hwmon1/name 
pwmfan
```

**Comment by chkohn** [comment]
@dnotq thanks for reaching out.

the k26 SOM does indeed not have the ina device. It is available on the vision (kv) and robotics (kr) carrier cards only. If you are using the k26 bsp, this behavior is expected. If you were to use the kv260 or kr260 bsp, then the ina device will be brought in through the carrier card specific device tree and platformstats will report out the ina statistics.

we can add a comment in the code as well as the readme to explain the behavior but it is as expected.

cc: @vshpatel

**Comment by dnotq** [comment]
Thanks, having that information would be nice.  Also, being able to suppress the missing device message when not using the Vision or Robotics kits would be helpful, otherwise the tool is not very useful for anyone using the KRIA for their own designs.

I was also under the assumption that the KRIA SOM does have on-board power monitoring via the DA9062 PMIC, DA9130 PMIC, and DA9131 PMIC, as specified in DS987 (KRIA K26 SOM Data Sheet) on pg. 8.  Without SOM schematics (which are not available AFAIK), extracting useful information from those devices would have to come from Xilinx, and it seems like this tool would be a good place to provide that information.

**Comment by chkohn** [comment]
we can look into adding a switch that allows the user to suppress the message or simply only print the output if the device is present. can you provide the complete sample output for your scenario?

The PMICs you mentioned don't allow per rail supply current monitoring, that's why the ina260 was added on the carrier cards for SOM level power telemetry. You could mirror the ina260 usage on a custom carrier card if that is desired.

And you are right, the K26 schematics are not public.

**Comment by dnotq** [comment]
Suppression of the message if the device is not found would be nice, and only display an error if the device is found but not responding, or whatever makes sense in that case.

The complete output for the command line on my K26 is:

```
root@xilinx-k26-som-20222:~# xlnx_platformstats -a
CPU Utilization
CPU0    :     0.000000%
CPU1    :     0.000000%
CPU2    :     0.000000%
CPU3    :     0.000000%

RAM Utilization
MemTotal      :     4026652 kB
MemFree       :     3870644 kB
MemAvailable  :     3826800 kB

Swap Mem Utilization
SwapTotal    :    0 kB
SwapFree     :    0 kB

no hwmon device found for ina260_u14 under /sys/class/hwmon
AMS CTRL
System PLLs voltage measurement, VCC_PSLL               :     1196 mV
PL internal voltage measurement, VCC_PSBATT             :     716 mV
Voltage measurement for six DDR I/O PLLs, VCC_PSDDR_PLL :     1797 mV
VCC_PSINTFP_DDR voltage measurement                     :     843 mV

PS Sysmon
LPD temperature measurement                             :     32 C
FPD temperature measurement (REMOTE)                    :     30 C
VCC PS FPD voltage measurement (supply 2)               :     845 mV
PS IO Bank 500 voltage measurement (supply 6)           :     1787 mV
VCC PS GTR voltage                                      :     854 mV
VTT PS GTR voltage                                      :     1800 mV

PL Sysmon
PL temperature                                          :     30 C

CMA Mem Utilization
CmaTotal   :     921600 kB
CmaFree    :     918684 kB

CPU Frequency
CPU0    :    1333.333008 MHz
CPU1    :    1333.333008 MHz
CPU2    :    1333.333008 MHz
CPU3    :    1333.333008 MHz
```

Of course the web interface that starts as part of the stock K26 BSP segfaults as soon as you try to load the page due to the other error I submitted.  I suspect some of the graphs on the output webpage will be empty if the INA260 is not found.

I did hack the tool just to see what the webpage might look like if it was working, and it spams the console with the "device found for ina260_u14" message (I just set fp_out to stdio by default).

As for mirroring the use of the INA260 on our SOM Carrier card, that might be an option if those parts were available anywhere (and with enough quantity to cover production).  As it goes right now, we had to use what was available, and most of the parts on the Vision and Robotics boards (ETH PHY, Power ICs, etc.) are still out of stock at most legit distributors.

**Comment by chkohn** [comment]
thank you for the detailed information, that's very useful. you are right, we need to look at the dashboard and handle the use case of the ina260 not being present there as well. doing this all dynamically will be best. overall, none of this should be too complicated. we have some deadlines at the end of the month / first week of June, so we'll only get to this in 3-4 weeks from now.

as for the ina260 or equivalent telemetry IC. as long as the device can be registered as a hwmon device, adjusting the application should be pretty straightforward. we can attempt and make platformstats more generic if we receive sufficient detail about the specific use cases. we are also welcoming contributions and are more than happy to review and merge code as applicable.

**Comment by dnotq** [comment]
I would be interested in learning how to make our specific power monitor ICs (Microchip PAC195X) show up as hwmon devices.  Can you point me to a starting point or reference?

Having a more generic platformstats would nice, and I'm happy to provide information about our use case where I can.

**Comment by chkohn** [comment]
@dnotq there are two relevant subsystems in the kernel to check or consider for driver support: iio and hwmon. there is some overlap between these two and in some cases either subsystem could be used. 

in our case, we wrote an iio linux driver for the ina260 which you can reference here:
https://github.com/Xilinx/linux-xlnx/blob/master/drivers/iio/adc/ina260-adc.c

there is some legacy software that uses the hwmon interface like lmsensors and for that, the iio-hwmon bridge driver can be used to provide generic plumbing from iio into hwmon:
https://github.com/Xilinx/linux-xlnx/blob/3a2a9dcee70777a85b3952269c47e6eb65779b78/Documentation/devicetree/bindings/hwmon/iio-hwmon.yaml#L4

if you check the kv or kr carrier card device tree, here is the ina260 node which maps to the iio driver:
https://github.com/Xilinx/linux-xlnx/blob/master/arch/arm64/boot/dts/xilinx/zynqmp-sck-kv-g-revB.dts#L35-L40
and here is the iio-hwmon bridge associated with the ina260 device:
https://github.com/Xilinx/linux-xlnx/blob/master/arch/arm64/boot/dts/xilinx/zynqmp-sck-kv-g-revB.dts#L46-L49

platformstats is using the hwmon interface to read the power, current and voltage from the ina260 device. as long as the telemetry device uses the same hwmon interface, the application changes are very minor and we can look into making it more generic if we have another example device to test against here. The parts that are currently hard-coded are the device name (ina260_u14) and the channel names (power1_input etc.). This could be read from a board specific config file instead. 

hope this helps!

**Comment by dnotq** [comment]
Thank you for the detailed info!  I'm not sure when it will move to the top of the priority list, but I will certainly look into this since power monitoring is important in our application.

**Comment by vshpatel** [comment]
Fixed via https://github.com/Xilinx/xlnx_platformstats/commit/28f3b317e54cb4bafb5a17116121795bed953fb7
